### ISSUE TITLE
Can we move alumni to content?

### ISSUE THREAD

**Issue by msaharia** [hydrosenselab/official-website#4]
Can we move alumni.json to content/alumni?

Just to keep things organized.

**Comment by shreyagupta30** [comment]
Hello sir!
According to the hugo docs, we can't add a custom file in the content folder, since it follows a format (index.md and then followed by different md files). So for purpose of data, we need to keep it in different folder.
[https://gohugo.io/templates/data-templates/](https://gohugo.io/templates/data-templates/)

**Comment by msaharia** [comment]
Understood. That's fine then.

**Comment by shreyagupta30** [comment]
Okay sir!
